apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservice
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitea.ajotham.link/Jotham/micro-services-demo.git
    targetRevision: main
    path: ./k8-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: microservice
  syncPolicy:
   automated: 
     selfHeal: true
     prune: true
   syncOptions:
   - CreateNamespace=true
