- name: Configure Kubernetes cluster nodes
  hosts: all     
  become: yes
  become_user: root
  gather_facts: yes
  roles:
    - common                 

- name: Configure Kubernetes master node
  hosts: master
  become: yes
  become_user: root
  roles:
    - master              

- name: Configure Kubernetes worker nodes
  hosts: workers
  become: yes
  become_user: root
  roles:
    - worker                  

- name: Label worker nodes
  hosts: master
  become: yes
  become_user: root
  roles:
    - utils

- name: Reset and Setup Again
  hosts: master
  become: yes
  become_user: root
  roles:
    - reset-master  

- name: Rejoin Workers
  hosts: workers
  become: yes
  become_user: root
  roles:
    - reset-worker 

- name: Final Setup
  hosts: master
  become: yes
  become_user: root
  roles:
    - final-setup 

- name: Final Setup
  hosts: master
  become: yes
  become_user: root
  roles:
    - argocd-setup
    - argocd-app